Repository wecode-bootcamp-korea/24-2nd-TomorrowsNotebook-frontend, pull requests merged in 2021-09, with the labels that each got.

#1 [24기 조성환] [feature/loginPage] Add : 로그인 페이지 레이아웃 완료
  .gitignore
  package-lock.json
  package.json
  public/images/logo.png
  public/index.html
  src/pages/Login/ImageUrlComponent/ImageUrlComponent.js
  src/pages/Login/Login.js
Labels: Status: Accepted

#2 [24기 주철진][feature/main] Add : 메인 페이지 레이아웃 구현 중
  public/images/dog.png
  public/index.html
  src/components/BooksTap/Book.js
  src/components/BooksTap/BookLayout.js
  src/components/BooksTap/Books.js
  src/components/BooksTap/BooksTap.js
  src/pages/Main/Banners/BannerList.js
  src/pages/Main/Banners/Banners.js
  src/pages/Main/CartoonBanner/CartoonBanner.js
  src/pages/Main/Main.js
  src/pages/Main/SubHeader/SubHeader.js
  src/pages/Main/TodaysBook/BookCard.js
  src/pages/Main/TodaysBook/CommentCard.js
  src/pages/Main/TodaysBook/TodaysBook.js
  src/pages/Main/TodaysSentence/TodaysSentence.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#4 [24기 조성환] [feature/loginPage] Fix : 서버와 통신 테스트 완료
  public/index.html
  src/config.js
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#6 [24기 강연옥] ADD: Viewer 페이지 이동 기능 구현 완료
  package-lock.json
  package.json
  src/Routes.js
  src/pages/Search/FontAwesome.js
  src/pages/Search/Search.js
  src/pages/Search/Suggestions.js
  src/pages/Viewer/Materials.js
  src/pages/Viewer/PageSlider.js
  src/pages/Viewer/Viewer.js
  src/pages/Viewer/example.pdf
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#7 [24기 주철진]Add : 책 상세페이지 구현 중
  public/data/detail.json
  public/index.html
  src/components/Modal/DeleteModal.js
  src/components/Modal/ModalLayout.js
  src/components/Modal/Potal.js
  src/pages/Detail/Alert.js
  src/pages/Detail/AsideMenu/AsideMenu.js
  src/pages/Detail/BookInfoTap/BOOK_DATA.js
  src/pages/Detail/BookInfoTap/BookDescription.js
  src/pages/Detail/BookInfoTap/BookInfoTap.js
  src/pages/Detail/BookSummary/BookSummary.js
  src/pages/Detail/Comments/Comment.js
  src/pages/Detail/Comments/Comments.js
  src/pages/Detail/Comments/InputForm.js
  src/pages/Detail/Detail.js
  src/pages/Search/FontAwesome.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#9 [24기 조성환] [feature/NavBarPage] FIX : 상단, 좌측 네브바 레이아웃 수정 및 로그인/로그아웃 버튼 수정
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#10 [24기 주철진] Add : 메인 페이지 API 통신 완료 / 동적라우팅 추가
  src/Routes.js
  src/components/BooksTap/Book.js
  src/components/BooksTap/BookLayout.js
  src/components/BooksTap/Books.js
  src/components/BooksTap/BooksTap.js
  src/components/Footer/Footer.js
  src/config.js
  src/pages/Main/Banners/BannerList.js
  src/pages/Main/Banners/Banners.js
  src/pages/Main/Main.js
  src/pages/Main/PreferenceTap/Genres.js
  src/pages/Main/PreferenceTap/GridBookCard.js
  src/pages/Main/PreferenceTap/PreferenceTap.js
  src/pages/Main/TodaysBook/BookCard.js
  src/pages/Main/TodaysBook/CommentCard.js
  src/pages/Main/TodaysBook/TodaysBook.js
  src/utils/api.js
Labels: Status: 리뷰 요청

#12 [24기 조성환] [feature/NavBarPage] FIX : navbar 레이아웃 및 아이콘 수정
  package-lock.json
  package.json
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#11 [24기 강연옥] ADD: 검색창 필수 기능 구현 완료
  public/data/mockdata.json
  src/components/FontAwesome.js
  src/pages/Search/Categories.js
  src/pages/Search/DefaultView.js
  src/pages/Search/KeywordView.js
  src/pages/Search/ResultView.js
  src/pages/Search/Search.js
  src/pages/Search/SearchBooks.js
  src/pages/Search/SearchFilter.js
  src/pages/Search/SearchMain.js
  src/pages/Search/Suggestions.js
  src/pages/Viewer/Materials.js
  src/pages/Viewer/Viewer.js
Labels: Status: 리뷰 요청

#14 [24기 강연옥] ADD: Viewer 필수 구현 기능 완료
  src/Routes.js
  src/pages/Search/SearchFilter.js
  src/pages/Search/SearchMain.js
  src/pages/Viewer/IndexModal.js
  src/pages/Viewer/Materials.js
  src/pages/Viewer/Modal.js
  src/pages/Viewer/PageSlider.js
  src/pages/Viewer/Viewer.js
  src/pages/Viewer/example.pdf
Labels: Status: 리뷰 요청

#8 [24기 조성환] [feature/mybooksPage] Add : mybooksPage
  public/data/mybooks.json
  src/pages/MyBooks/MyBooks.js
  src/pages/MyBooks/MyBooksComponent/MybooksNav/MybooksNav.js
  src/pages/MyBooks/MyBooksComponent/MybooksNav/ShelvesNav.js
  src/pages/MyBooks/MyBooksComponent/MybooksNav/TotalBooksNav.js
  src/pages/MyBooks/MyBooksComponent/Shelf/BookCovers.js
  src/pages/MyBooks/MyBooksComponent/Shelf/MainShelf.js
  src/pages/MyBooks/MyBooksComponent/Shelf/Shelves.js
  src/pages/MyBooks/MyBooksComponent/Top/Top.js
  src/pages/MyBooks/MyBooksComponent/TotalBooks/Books.js
Labels: Status: 리뷰 요청

#13 [24기 주철진] Add : 서재 관련 기능 구현
  public/data/libraryList.json
  public/index.html
  src/Routes.js
  src/components/Modal/DeleteModal.js
  src/components/Modal/LibraryModal.js
  src/components/Modal/ModalLayout.js
  src/components/Modal/ToMyBooksModal.js
  src/components/Modal/component/CheckItem.js
  src/pages/Detail/AsideMenu/AsideMenu.js
  src/pages/Detail/BookInfoTap/BookDescription.js
  src/pages/Detail/BookInfoTap/BookInfoTap.js
  src/pages/Detail/BookSummary/BookSummary.js
  src/pages/Detail/Comments/Comment.js
  src/pages/Detail/Comments/Comments.js
  src/pages/Detail/Comments/InputForm.js
  src/pages/Detail/Detail.js
  src/pages/Main/Main.js
  src/pages/Search/FontAwesome.js
Labels: Status: Rebase 요청

#15 [24기 주철진] Modify : 메인 페이지 슬라이더 함수 변경
  src/components/BooksTap/Book.js
  src/components/BooksTap/Books.js
  src/components/BooksTap/BooksTap.js
  src/pages/Main/Main.js
  src/pages/Main/PreferenceTap/GridBookCard.js
  src/pages/Main/PreferenceTap/PreferenceTap.js
  src/pages/Main/TodaysBook/BookCard.js
  src/pages/Main/TodaysBook/TodaysBook.js
Labels: Status: 리뷰 요청

#16 [24기 조성환] [feature/mybooksPage] FIX : mybooks페이지 error 해결
  src/Routes.js
  src/pages/MyBooks/MyBooks.js
  src/pages/MyBooks/MyBooksComponent/MybooksNav/MybooksNav.js
  src/pages/MyBooks/MyBooksComponent/MybooksNav/ShelvesNav.js
  src/pages/MyBooks/MyBooksComponent/Shelf/BookCovers.js
  src/pages/MyBooks/MyBooksComponent/TotalBooks/Books.js
Labels: Status: 리뷰 요청
